name = "Exfiltrator"
uuid = "8fb92a4a-34c4-45cc-956f-769d12f66c92"
authors = ["Antoine Levitt <antoine.levitt@gmail.com> and contributors"]
version = "0.1.1"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
